In [2]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [4]:
# element-wise operations
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y; x - y
x * y; x / y

array([0.5, 0.5, 0.5])

In [7]:
# N차원 배열
A = np.array([[1,2], [3,4]])
print(A)
A.shape
A.dtype
B = np.array([[3,0], [0,6]])
A + B
A * B

[[1 2]
 [3 4]]


array([[ 3,  0],
       [ 0, 24]])

In [8]:
# broadcasting
A = np.array([[1,2], [3,4]])
B = np.array([10,20])
A * B

array([[10, 40],
       [30, 80]])

In [10]:
# 원소 접근
X = np.array([[51,55], [14,19], [0,4]])
X[0]        # 0행
X[0][1]     # (0,1) 위치의 원소

55

In [13]:
for row in X:
    print(row)
X = X.flatten()         # X를 1차원 배열로 변환 (평탄화)
print(X)
X[np.array([0, 2, 4])]  # 인덱스가 0, 2, 4인 원소 얻기 -> array([51, 14, 0])
X[X > 15]               # array([51, 55, 19])

51
55
14
19
0
4
[51 55 14 19  0  4]


array([51, 55, 19])